logLevel: DEBUG

# GCLOUD CONFIGURATION
project: cs2018-ap
network: cs2018-ap-network
diskSizeGb: 50
numWorkers: 1
maxNumWorkers: 1

# REDIS CONFIGURATION
redisHost: 10.20.40.41
redisPort: 6379
redisMaxConnect: 10000

