# GCLOUD CONFIGURATION
project: sentifi-backoffice-qa
network: sentifi-backoffice-qa-network
diskSizeGb: 50

redisHost: 10.20.40.41
redisPort: 6379
redisMaxConnect: 10000

# DATAFLOW
runner: DataflowRunner
streaming: true
unbounded: true
jobName: simple-streaming

autoscalingAlgorithm: THROUGHPUT_BASED

# NETWORK
zone: europe-west1-b
subnetwork: regions/europe-west1/subnetworks/europe-west1
region: europe-west1

numWorkers: 1
maxNumWorkers: 1
