spring:
  jpa:
    show-sql: true
    hibernate:
      jdbc:
        batch_size: 50
        batch_versioned_data: true
      order_inserts: true
      order_updates: true
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        temp.use_jdbc_metadata_defaults: false

  data.rest.basePath: /api
  thymeleaf.cache: false
  devtools.restart.exclude: src/test/**
  jackson.date-format: yyyy-MM-dd'T'HH:mm:ssZ
logging.level.: INFO
